"""add_notification_models

Revision ID: 58ec6ae3b5c3
Revises: f84694c3537e
Create Date: 2025-12-26 16:56:45.055689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58ec6ae3b5c3'
down_revision: Union[str, None] = 'f84694c3537e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_sent_at', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_therapist_id', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_push_tokens_expo_push_token', table_name='push_tokens')
    op.drop_index('ix_push_tokens_id', table_name='push_tokens')
    op.drop_index('ix_push_tokens_therapist_id', table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_index('ix_therapist_notification_settings_id', table_name='therapist_notification_settings')
    op.drop_index('ix_therapist_notification_settings_therapist_id', table_name='therapist_notification_settings')
    op.drop_table('therapist_notification_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapist_notification_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('therapist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sound_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('vibration_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('new_order_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('order_cancelled_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('order_completed_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('system_message_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('new_order_sound', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('new_order_vibration_pattern', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('do_not_disturb_periods', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], name='therapist_notification_settings_therapist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='therapist_notification_settings_pkey')
    )
    op.create_index('ix_therapist_notification_settings_therapist_id', 'therapist_notification_settings', ['therapist_id'], unique=True)
    op.create_index('ix_therapist_notification_settings_id', 'therapist_notification_settings', ['id'], unique=False)
    op.create_table('push_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('therapist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expo_push_token', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('device_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('app_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], name='push_tokens_therapist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='push_tokens_pkey')
    )
    op.create_index('ix_push_tokens_therapist_id', 'push_tokens', ['therapist_id'], unique=True)
    op.create_index('ix_push_tokens_id', 'push_tokens', ['id'], unique=False)
    op.create_index('ix_push_tokens_expo_push_token', 'push_tokens', ['expo_push_token'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('therapist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('NEW_ORDER', 'ORDER_CANCELLED', 'ORDER_COMPLETED', 'SYSTEM_MESSAGE', 'PAYMENT_SUCCESS', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'READ', name='notificationstatus'), autoincrement=False, nullable=False),
    sa.Column('sent_via', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.id'], name='notifications_therapist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_therapist_id', 'notifications', ['therapist_id'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_sent_at', 'notifications', ['sent_at'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###

