"""add_therapist_customer_reviews_table

Revision ID: a1f09d4f9beb
Revises: de687e177d24
Create Date: 2025-12-28 08:00:37.324602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f09d4f9beb'
down_revision: Union[str, None] = 'de687e177d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

