"""change_therapist_is_active_to_status_enum

Revision ID: f84694c3537e
Revises: 
Create Date: 2025-12-26 08:16:33.176808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84694c3537e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 步骤 1: 添加新的 status 列（先设置为可空）
    op.add_column('therapists', sa.Column('status', sa.Enum('ONLINE', 'BUSY', 'OFFLINE', name='therapiststatus'), nullable=True))
    
    # 步骤 2: 迁移数据 - 将所有技师设置为 offline（安全的默认值）
    # 注意：即使 is_active=true，也设置为 offline，让技师登录后主动上线
    op.execute("""
        UPDATE therapists 
        SET status = 'OFFLINE'
        WHERE status IS NULL
    """)
    
    # 步骤 3: 设置 NOT NULL 约束
    op.alter_column('therapists', 'status', nullable=False)
    
    # 步骤 4: 删除旧的 is_active 列
    op.drop_column('therapists', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 步骤 1: 恢复 is_active 列
    op.add_column('therapists', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    
    # 步骤 2: 根据 status 恢复 is_active 的值
    # online -> true, 其他 -> false
    op.execute("""
        UPDATE therapists 
        SET is_active = CASE 
            WHEN status = 'ONLINE' THEN true
            ELSE false
        END
    """)
    
    # 步骤 3: 设置 NOT NULL 约束
    op.alter_column('therapists', 'is_active', nullable=False)
    
    # 步骤 4: 删除 status 列
    op.drop_column('therapists', 'status')
    # ### end Alembic commands ###

